apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-app
  template:
    metadata:
      labels:
        app: train-app
    spec:
      containers:
        - name: train-app
          image: train-ticket-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080